### ISSUE TITLE
Manage all Domains pointing to the iredmail host

### ISSUE THREAD

**Issue by modir** [iredmail/iRedMail#127]
We have several autoconfig and autodiscover domains pointing to this server. I would like to manage those domains somewhere in the web interface so that Let's encrypt can automatically create certificates for those domains as well.

**Comment by iredmail** [comment]
iRedMail or iRedAdmin-Pro don't manage ssl certs yet, and still no plan for this shortly.
How would you like to manage cert in a web UI?

**Comment by modir** [comment]
I don 't want to have the management of the certs itself in the GUI.. What I want is that for each domain in the GUI. iredadmin automatically creates in the httpd config file an entry for autdiscover.domain.com and autoconfig.domain.com. This way the certbot can automatically include those domains in the next run.

Ideally it is a checkbox in the domain config page of the GUI:
[x] Create automatic config in httpd

Or something similar.

**Comment by iredmail** [comment]
Although we can work out a solution like let Nginx load virtual host config files from a directory which is writable by iRedAdmin(-Pro), but this is not the point i want to talk about.

Let's assume iRedAdmin(-Pro) created the Nginx config file(s) for `autoconfig.<domain>` and `autodiscover.<domain>`, we may have few problems.

1. if we add parameters to enable https support for them, the ssl cert/key are definitely missing at this stage. It will cause Nginx fail to start / restart / reload due to missing cert/key files.
1. Another problem is requesting cert. The procedure is:
    1. Add the DNS records (`autoconfig.`, `autodiscover.`) and point to iRedMail server.
    2. Run `certbot` or similar tool to request cert.

iRedAdmin-Pro can NOT add the DNS records for you since it doesn't know how to add the record with either a DNS server running in LAN, or a DNS hosting vendor like namecheap.com, godaddy.com etc, so you can not request cert right after created the domain with iRedAdmin-Pro.

Dead end?

**Comment by modir** [comment]
I don't need the SSL certs.. I need the vhost configs for HTTP (port 80). certbot creates then the configs for HTTPS (port 443). And I don't need the DNS records it selves either. They are managed by another system. That's why I need the checkbox on the domain so I can say which domains do have the DNS records set. Because from then on I need the HTTP entries in nginx so that certbot can create the HTTPS entries.

**Comment by iredmail** [comment]
Here's another solution which i think it's much easier and don't rely on iRedAdmin-Pro or anything else:

Write a script to:

- Query all mail domains from iRedMail SQL/LDAP database
- For each domain name, check its `autoconfig.` and `autodiscover.` DNS records, if it's pointed to IP address of this iRedMail server, then create Nginx config file and request ssl cert.

You can create a catch-all Nginx virtual host config file with parameter `server_name autoconfig.* autodiscover.*;` (`*`, literally, not a placeholder). I suppose you already have the PHP files used to serve http requests?

If you prefer one domain name per host config file, not that hard too. :)

**Comment by modir** [comment]
Sadly this solution does not work for me. We have about 60 domains. Some of them point directly to the mail server others point first to an external spam filter or first to a reverse proxy. Even others are not managed by us and the client sometimes does not set those DNS records. It doesn't make sense to scan them each time. So we need this information in a database or LDAP.

**Comment by modir** [comment]
Why was this issue closed without a comment?

**Comment by iredmail** [comment]
No plan for this in iRedMail or iRedAdmin(-Pro). Better use a shell/python/perl/... script for this and run in cron.
