### ISSUE TITLE
[feature request] Configured Page about Remote LDAP Server

### ISSUE THREAD

**Issue by WildfootW** [iredmail/iRedMail#58]
I guess most companies have existing AD/LDAP Server. It would be useful to have a custom page.
z.B. (I print screen from QNAP's application)
![image](https://user-images.githubusercontent.com/11520473/88189388-9618dc00-cc6b-11ea-9e9d-f5ff9dcc123e.png)

**Comment by iredmail** [comment]
Do I understand correctly that you want few pages to describe how each application can use the OpenLDAP server running on iRedMail as a remote LDAP server? No plan  for this shortly, but if you have something to share, feel free to send us some PR for the document site:
https://GitHub.com/iredmail/docs

**Comment by Scottpedia** [comment]
@iredmail 

Hello

I have a similar question like that. Say I already have an openldap server running in one of the networked docker containers. And can I deploy the iredmail also as a docker containter that makes use of the existing ldap server, instead of the one created by iredmail installation wizard? This way, I can deploy more applications, like a file storage server, that connect to the shared ldap server. If this can be done, where do I find the configurations for such an "external" idap server?
