### ISSUE TITLE
Create Let's Encrypt certificate at install

### ISSUE THREAD

**Issue by modir** [iredmail/iRedMail#61]
Right now when iRedMail is installed totally new one of the first steps the installer is doing is to create an self-signed SSL certificate. It would be nicer if the installer would create a Let's encrypt certificate. Then there are no problems with the browsers afterwards when connecting to the web GUI later.

**Comment by iredmail** [comment]
We have a tutorial to guide sysadmin to request Let's Encrypt cert: https://docs.iredmail.org/letsencrypt.html

Offering the option to request cert during iRedMail installation does make ssl setup easier, the problem is, many people are still quite new in email hosting world, they may not even have correct DNS A record for the server hostname. this will cause some problem and the installation will make them confused.

**Comment by modir** [comment]
Exactly because of your reasons I would have a silent failback to creating a self-signed certificate. This way the better will happen if possible and else we go with what we already have for a while now.

**Comment by iredmail** [comment]
I will try to finish this in next iRedMail release. :)
